main: me.flail.SlashPlayer.SlashPlayer
name: SlashPlayer
author: [FlailoftheLord, WulfGamesYT]
description: player managment GUI system
version: 2.1.2
api-version: 1.13
softdepend: [Vault, WorldEdit, MicroCommands]

commands:
  slashplayer:
    usage: /slashplayer [reload:report:player-name]
    description: opens the player list menu
    aliases: [player, sp, report, reportplayer, spr, reports, spunban]
   
  ouch:
    description: ouch!
  
permissions:

  slashplayer.op:
    description: Gives access to everything! same as slashplayer.*
    default: false
    children:
      slashplayer.command: true
      slashpalyer.interactopen: true
      slashplayer.rank: true
      slashplayer.exempt: true
      slashpalyer.notify: true
      slashplayer.staff: true
      slashplayer.ban: true
      slashplayer.kick: true
      slashplayer.mute: true
      slashplayer.kill: true
      slashplayer.clearinventory: true
      slashplayer.whitelist: true
      slashplayer.fly: true
      slashplayer.gamemode: true
      slashplayer.gamemode.all: true
      slashplayer.freeze: true
      slashplayer.summon: true
      slashplayer.teleport: true
      slashplayer.heal: true
      slashplayer.feed: true

  slashplayer.command:
    description: use the /player command
    default: op
  slashplayer.interactopen:
    description: click a player to open their GUI menu
    default: op
    
  slashplayer.rank:
    description: base for rank settings
    default: true
    
  slashplayer.rank.0:
    description: default rank
    default: true
      
  # This makes the permisison holder exempt from all kills, mutes, bans and inventory clears.
  slashplayer.exempt:
    description: exempt from bans, mutes and freezes
    default: op
    children:
      slashplayer.exempt.kill: true
      slashplayer.exempt.kick: true
      slashpalyer.exempt.mute: true
      slashplayer.exempt.freeze: true
      slashplayer.exempt.ban: true
    
  slashplayer.exempt.kick:
    description: exempt ONLY from kicks.
    default: op
  slashplayer.exempt.mute:
    description: exempt ONLY from mutes.
    default: op
  slashplayer.exempt.ban:
    description: exempt ONLY from bans.
    dfault: op
  slashplayer.exempt.kill:
    description: immune to kills.
    default: op
  slashplayer.exempt.freeze:
    description: immune to being frozen.
    default: op
    
  slashplayer.notify:
    description: notifies these players of unbans and unmutes
    default: true
  slashplayer.staff:
    description: permission to receive and process reports
    default: op
    
  slashplayer.ban:
    description: ability to ban and unban players through the gui
    default: op
  slashplayer.mute:
    description: ability to mute and unmute players through the gui
    default: op
  slashplayer.freeze:
    description: ability to freeze and unfreeze players through the gui
    default: op
  slashplayer.gamemode:
    description: ability to change a players' gamemode through the gui
    default: op
    
  slashplayer.gamemode.all:
    default: op
    description: all gamemodes
    children:
      slashplayer.gamemode.survival: true
      slashpalyer.gamemode.adventure: true
      slashplayer.gamemode.creative: true
      slashplayer.gamemode.spectator: true
      
  slashplayer.gamemode.survival:
    default: op
    
  slashplayer.gamemode.adventure:
    default: op
    
  slashplayer.gamemode.creative:
    default: op
    
  slashplayer.gamemode.spectator:
    default: op
    
    
  slashplayer.heal:
    description: ability to heal a player through the gui
    default: op
  slashplayer.feed:
    description: ability to feed a player through the gui
    default: op
  slashplayer.teleport:
    description: ability to teleport to the player through the gui
    default: op
  slashplayer.summon:
    description: ability to summon the player to you through the gui
    default: op
  slashplayer.kick:
    description: ability to kick a player through the gui
    default: op
  slashplayer.fly:
    description: ability to toggle the fly of the player through the gui
    default: op
  slashplayer.kill:
    description: ability to kill the player through the gui
    default: op
  slashplayer.clearinventory:
    description: ability to clear and restore a players' inventory
    default: op
  slashplayer.whitelist:
    description: ability to add and remove players from the whitelist
    default: op
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  