main: me.flail.SlashPlayer.SlashPlayer
name: SlashPlayer
author: [FlailoftheLord, WulfGamesYT]
description: player managment GUI system
version: 2.1.0-BETA-1
api-version: 1.13
softdepend: [Vault, WorldEdit]

commands:
  slashplayer:
    usage: /slashplayer [reload:report:player-name]
    description: opens the player list menu
    aliases: [player, sp, report, reportplayer, spr, reports]
    
permissions:
  slashplayer.command:
    description: use the /player command
    default: op
      
  # This makes the permisison holder exempt from all kills, mutes, bans and inventory clears.
  slashplayer.exempt:
    description: exempt from bans, mutes and freezes
    default: op
  slashplayer.notify:
    description: notifies these players of unbans and unmutes
    default: true
  slashplayer.staff:
    description: permission to receive and process reports
    default: op
    
  slashplayer.ban:
    description: ability to ban and unban players through the gui
    default: op
  slashplayer.mute:
    description: ability to mute and unmute players through the gui
    default: op
  slashplayer.freeze:
    description: ability to freeze and unfreeze players through the gui
    default: op
  slashplayer.gamemode:
    description: ability to change a players' gamemode through the gui
    default: op
    
  slashplayer.gamemode.all:
    default: op
    description: all gamemodes
    children:
      slashplayer.gamemode.survival: true
      slashpalyer.gamemode.adventure: true
      slashplayer.gamemode.creative: true
      slashplayer.gamemode.spectator: true
    
  slashplayer.heal:
    description: ability to heal a player through the gui
    default: op
  slashplayer.feed:
    description: ability to feed a player through the gui
    default: op
  slashplayer.teleport:
    description: ability to teleport to the player through the gui
    default: op
  slashplayer.summon:
    description: ability to summon the player to you through the gui
    default: op
  slashplayer.kick:
    description: ability to kick a player through the gui
    default: op
  slashplayer.fly:
    description: ability to toggle the fly of the player through the gui
    default: op
  slashplayer.kill:
    description: ability to kill the player through the gui
    default: op
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  